export const strings = {
  en: {
    addYourProduct: "Add your product",
    addProduct: "Add Product",
    shopList: "Shop List",
    login: "Login",
    logout: "Logout",
    add: "Add",
    Product: "Product",
    quantity: "Quantity",
    languageReverse: "Change to Polish",
    addedSuccessfully: "Item added to the list",
    addFaultName: "Product name is required",
    addFaultQuantity: "Product quantity is required (between 1 and 100)",
    welcome: "Welcome ",
  },
  pl: {
    addYourProduct: "Dodaj pierwszy produkt",
    addProduct: "Dodaj Produkt",
    shopList: "Lista Zakupów",
    login: "Zaloguj",
    logout: "Wyloguj",
    add: "Dodaj",
    Product: "Produkt",
    quantity: "Ilość",
    languageReverse: "Zmień na Angielski",
    addedSuccessfully: "Produkt dodany do listy",
    addFaultName: "Nazwa produktu jest wymagana",
    addFaultQuantity: "Ilość produktu jest wymagana (pomiędzy 1 a 100)",
    welcome: "Witaj ",
  },
};
